### ISSUE TITLE
Support for Angular 14

### ISSUE THREAD

**Issue by chrisleyva** [Cordobo/angularx-qrcode#179]
Hello,

Thank you for this great library. I'm sure there are plans to support the latest Angular release (14), I just wanted to create an issue to show that there is need for it in the community 😄 .

Thanks again!

**Comment by Cordobo** [comment]
Hi @chrisleyva 

Support for angular 14 has landed. Happy coding!

**Comment by eXpertise7** [comment]
@Cordobo Hey, just a friendly advice, I'd suggest writing changelog docs / release note comments on version upgrades (could be here: https://github.com/Cordobo/angularx-qrcode/tags ). I believe it could be a hassle, since you're not getting paid and I understand if you won't do it, but people would have easier time migrating this library to newer versions.

Just migrating angularx-qrcode from 2.3.5 to 14.0.0 and seeing this errors, but ye, I've figured it out that property `size` is `width ` now and `level ` is `errorCorrectionLevel`.
![image](https://user-images.githubusercontent.com/17203747/198144111-dfcc5b9a-9ad1-41db-90c8-7a321a119101.png)


Thanks.

Kind regards,
Robert Medved

**Comment by Cordobo** [comment]
@eXpertise7 Hi, thanks for your comment. I had some hints in the code which logged debug messages to the console while in dev mode. If I remember right, I introduced them in V10 (where the breaking change happened and removed them in V14. 

With angular 15 released yesterday, might be worthwhile to reintegrate them into the code.

**Comment by araujomartin** [comment]
How I make a pull request to add imgsrc from Angular 12 version

**Comment by Cordobo** [comment]
@araujomartin 

angularx-qrcode 14 already supports imageSrc
https://github.com/Cordobo/angularx-qrcode/issues/183
