### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by c2ofh** [Cordobo/angularx-qrcode#33]
Is it able to remove the background, to get the qr code on a transparent background?

**Comment by c2ofh** [comment]
rgba(0, 0, 0, 0) as background works.

**Comment by pepsifan92** [comment]
The Parameter is _colorLight_. The docmentation (angular v17) says it's a String and you can set it to '#ffffffff' as a RGBA for the color of light module (background).

The last 2 digits are opacity. It's HEX with 8 digits instead of the usual 6 digits: Example for zero opacity: #FFFFFF**00**

So `<qr-code ... [lightColor]="'#FFFFFF00'">` makes it transparent.

**Comment by rbalet** [comment]
Update, this is now `colorLight="#FFFFFF00"`
